"""initial schema

Revision ID: 43d5c3985356
Revises: 
Create Date: 2026-09-18 16:21:49.166329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d5c3985356'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coa_number', sa.String(length=50), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.String(length=180), nullable=True),
    sa.Column('product', sa.String(length=180), nullable=False),
    sa.Column('cas_no', sa.String(length=40), nullable=True),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('test_status', sa.String(length=50), nullable=False),
    sa.Column('coa_status', sa.String(length=50), nullable=False),
    sa.Column('qc_approved', sa.Boolean(), nullable=False),
    sa.Column('qa_approved', sa.Boolean(), nullable=False),
    sa.Column('test_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tested_by', sa.String(length=120), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('document_reference', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coas_batch_number'), 'coas', ['batch_number'], unique=False)
    op.create_index(op.f('ix_coas_coa_number'), 'coas', ['coa_number'], unique=True)
    op.create_index(op.f('ix_coas_coa_status'), 'coas', ['coa_status'], unique=False)
    op.create_index(op.f('ix_coas_customer'), 'coas', ['customer'], unique=False)
    op.create_index(op.f('ix_coas_po_number'), 'coas', ['po_number'], unique=False)
    op.create_index(op.f('ix_coas_product'), 'coas', ['product'], unique=False)
    op.create_index(op.f('ix_coas_test_status'), 'coas', ['test_status'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_code', sa.String(length=50), nullable=False),
    sa.Column('equipment_name', sa.String(length=180), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('capacity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capacity_unit', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('maintenance_status', sa.String(length=50), nullable=False),
    sa.Column('last_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('utilization_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('assigned_reactor', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_code'), 'equipment', ['equipment_code'], unique=True)
    op.create_index(op.f('ix_equipment_equipment_name'), 'equipment', ['equipment_name'], unique=False)
    op.create_index(op.f('ix_equipment_equipment_type'), 'equipment', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_equipment_maintenance_status'), 'equipment', ['maintenance_status'], unique=False)
    op.create_index(op.f('ix_equipment_status'), 'equipment', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enquiry_id', sa.String(length=40), nullable=False),
    sa.Column('customer', sa.String(length=180), nullable=False),
    sa.Column('product', sa.String(length=180), nullable=False),
    sa.Column('cas_no', sa.String(length=40), nullable=True),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('regulatory_path', sa.String(length=180), nullable=True),
    sa.Column('tech_pack', sa.String(length=30), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('next_step', sa.String(length=255), nullable=True),
    sa.Column('development', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_customer'), 'leads', ['customer'], unique=False)
    op.create_index(op.f('ix_leads_enquiry_id'), 'leads', ['enquiry_id'], unique=True)
    op.create_index(op.f('ix_leads_market'), 'leads', ['market'], unique=False)
    op.create_index(op.f('ix_leads_product'), 'leads', ['product'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('customer', sa.String(length=180), nullable=False),
    sa.Column('product', sa.String(length=180), nullable=False),
    sa.Column('cas_no', sa.String(length=40), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_reactor', sa.String(length=50), nullable=True),
    sa.Column('production_status', sa.String(length=50), nullable=False),
    sa.Column('qc_status', sa.String(length=50), nullable=False),
    sa.Column('dispatch_status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_customer'), 'purchase_orders', ['customer'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index(op.f('ix_purchase_orders_product'), 'purchase_orders', ['product'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_number', sa.String(length=50), nullable=False),
    sa.Column('enquiry_id', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.String(length=180), nullable=False),
    sa.Column('product', sa.String(length=180), nullable=False),
    sa.Column('cas_no', sa.String(length=40), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_value_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_terms', sa.String(length=180), nullable=True),
    sa.Column('delivery_terms', sa.String(length=180), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quote_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_customer'), 'quotes', ['customer'], unique=False)
    op.create_index(op.f('ix_quotes_enquiry_id'), 'quotes', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_quotes_product'), 'quotes', ['product'], unique=False)
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_table('reactors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reactor_code', sa.String(length=50), nullable=False),
    sa.Column('reactor_name', sa.String(length=120), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_batch', sa.String(length=80), nullable=True),
    sa.Column('current_po_number', sa.String(length=50), nullable=True),
    sa.Column('current_product', sa.String(length=180), nullable=True),
    sa.Column('utilization_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactors_reactor_code'), 'reactors', ['reactor_code'], unique=True)
    op.create_index(op.f('ix_reactors_status'), 'reactors', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_number', sa.String(length=50), nullable=False),
    sa.Column('enquiry_id', sa.String(length=50), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.String(length=180), nullable=True),
    sa.Column('product', sa.String(length=180), nullable=False),
    sa.Column('cas_no', sa.String(length=40), nullable=True),
    sa.Column('batch_number', sa.String(length=80), nullable=True),
    sa.Column('sample_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('sample_type', sa.String(length=80), nullable=False),
    sa.Column('purpose', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatch_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_to', sa.String(length=180), nullable=True),
    sa.Column('courier', sa.String(length=180), nullable=True),
    sa.Column('tracking_number', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_customer'), 'samples', ['customer'], unique=False)
    op.create_index(op.f('ix_samples_enquiry_id'), 'samples', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_samples_po_number'), 'samples', ['po_number'], unique=False)
    op.create_index(op.f('ix_samples_priority'), 'samples', ['priority'], unique=False)
    op.create_index(op.f('ix_samples_product'), 'samples', ['product'], unique=False)
    op.create_index(op.f('ix_samples_sample_number'), 'samples', ['sample_number'], unique=True)
    op.create_index(op.f('ix_samples_status'), 'samples', ['status'], unique=False)
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=180), nullable=False),
    sa.Column('material_type', sa.String(length=100), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('warehouse', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('minimum_stock', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supplier', sa.String(length=180), nullable=True),
    sa.Column('last_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_batch_number'), 'stock_items', ['batch_number'], unique=False)
    op.create_index(op.f('ix_stock_items_material_code'), 'stock_items', ['material_code'], unique=True)
    op.create_index(op.f('ix_stock_items_material_name'), 'stock_items', ['material_name'], unique=False)
    op.create_index(op.f('ix_stock_items_material_type'), 'stock_items', ['material_type'], unique=False)
    op.create_index(op.f('ix_stock_items_status'), 'stock_items', ['status'], unique=False)
    op.create_table('supply_chain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_number', sa.String(length=50), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.String(length=180), nullable=True),
    sa.Column('material_name', sa.String(length=180), nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('source_location', sa.String(length=180), nullable=True),
    sa.Column('destination', sa.String(length=180), nullable=True),
    sa.Column('carrier', sa.String(length=180), nullable=True),
    sa.Column('tracking_number', sa.String(length=120), nullable=True),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expected_dispatch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_dispatch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_chain_customer'), 'supply_chain', ['customer'], unique=False)
    op.create_index(op.f('ix_supply_chain_material_code'), 'supply_chain', ['material_code'], unique=False)
    op.create_index(op.f('ix_supply_chain_material_name'), 'supply_chain', ['material_name'], unique=False)
    op.create_index(op.f('ix_supply_chain_po_number'), 'supply_chain', ['po_number'], unique=False)
    op.create_index(op.f('ix_supply_chain_priority'), 'supply_chain', ['priority'], unique=False)
    op.create_index(op.f('ix_supply_chain_shipment_number'), 'supply_chain', ['shipment_number'], unique=True)
    op.create_index(op.f('ix_supply_chain_status'), 'supply_chain', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=100), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'page', name='uq_role_page')
    )
    op.create_table('production_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_number', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('customer', sa.String(length=180), nullable=False),
    sa.Column('product', sa.String(length=180), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=True),
    sa.Column('required_quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('planned_quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reactor', sa.String(length=50), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('material_status', sa.String(length=50), nullable=False),
    sa.Column('planning_status', sa.String(length=50), nullable=False),
    sa.Column('production_status', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_plans_customer'), 'production_plans', ['customer'], unique=False)
    op.create_index(op.f('ix_production_plans_plan_number'), 'production_plans', ['plan_number'], unique=True)
    op.create_index(op.f('ix_production_plans_planning_status'), 'production_plans', ['planning_status'], unique=False)
    op.create_index(op.f('ix_production_plans_po_id'), 'production_plans', ['po_id'], unique=False)
    op.create_index(op.f('ix_production_plans_po_number'), 'production_plans', ['po_number'], unique=False)
    op.create_index(op.f('ix_production_plans_product'), 'production_plans', ['product'], unique=False)
    op.create_index(op.f('ix_production_plans_production_status'), 'production_plans', ['production_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('employee_id', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('customer', sa.String(length=180), nullable=True),
    sa.Column('product', sa.String(length=180), nullable=False),
    sa.Column('reactor', sa.String(length=50), nullable=True),
    sa.Column('planned_quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('produced_quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('production_status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator', sa.String(length=120), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['production_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_batches_batch_number'), 'production_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_production_batches_plan_id'), 'production_batches', ['plan_id'], unique=False)
    op.create_index(op.f('ix_production_batches_po_number'), 'production_batches', ['po_number'], unique=False)
    op.create_index(op.f('ix_production_batches_product'), 'production_batches', ['product'], unique=False)
    op.create_index(op.f('ix_production_batches_production_status'), 'production_batches', ['production_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_batches_production_status'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_product'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_po_number'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_plan_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_batch_number'), table_name='production_batches')
    op.drop_table('production_batches')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_production_plans_production_status'), table_name='production_plans')
    op.drop_index(op.f('ix_production_plans_product'), table_name='production_plans')
    op.drop_index(op.f('ix_production_plans_po_number'), table_name='production_plans')
    op.drop_index(op.f('ix_production_plans_po_id'), table_name='production_plans')
    op.drop_index(op.f('ix_production_plans_planning_status'), table_name='production_plans')
    op.drop_index(op.f('ix_production_plans_plan_number'), table_name='production_plans')
    op.drop_index(op.f('ix_production_plans_customer'), table_name='production_plans')
    op.drop_table('production_plans')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_supply_chain_status'), table_name='supply_chain')
    op.drop_index(op.f('ix_supply_chain_shipment_number'), table_name='supply_chain')
    op.drop_index(op.f('ix_supply_chain_priority'), table_name='supply_chain')
    op.drop_index(op.f('ix_supply_chain_po_number'), table_name='supply_chain')
    op.drop_index(op.f('ix_supply_chain_material_name'), table_name='supply_chain')
    op.drop_index(op.f('ix_supply_chain_material_code'), table_name='supply_chain')
    op.drop_index(op.f('ix_supply_chain_customer'), table_name='supply_chain')
    op.drop_table('supply_chain')
    op.drop_index(op.f('ix_stock_items_status'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_material_type'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_material_name'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_material_code'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_batch_number'), table_name='stock_items')
    op.drop_table('stock_items')
    op.drop_index(op.f('ix_samples_status'), table_name='samples')
    op.drop_index(op.f('ix_samples_sample_number'), table_name='samples')
    op.drop_index(op.f('ix_samples_product'), table_name='samples')
    op.drop_index(op.f('ix_samples_priority'), table_name='samples')
    op.drop_index(op.f('ix_samples_po_number'), table_name='samples')
    op.drop_index(op.f('ix_samples_enquiry_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_customer'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reactors_status'), table_name='reactors')
    op.drop_index(op.f('ix_reactors_reactor_code'), table_name='reactors')
    op.drop_table('reactors')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_product'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_enquiry_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_customer'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_product'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_customer'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_product'), table_name='leads')
    op.drop_index(op.f('ix_leads_market'), table_name='leads')
    op.drop_index(op.f('ix_leads_enquiry_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_customer'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_equipment_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_maintenance_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_type'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_name'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_code'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_coas_test_status'), table_name='coas')
    op.drop_index(op.f('ix_coas_product'), table_name='coas')
    op.drop_index(op.f('ix_coas_po_number'), table_name='coas')
    op.drop_index(op.f('ix_coas_customer'), table_name='coas')
    op.drop_index(op.f('ix_coas_coa_status'), table_name='coas')
    op.drop_index(op.f('ix_coas_coa_number'), table_name='coas')
    op.drop_index(op.f('ix_coas_batch_number'), table_name='coas')
    op.drop_table('coas')
    # ### end Alembic commands ###
